baseURL = "https://thomaslacour.github.io/blib/"
title = "Festival BLIB"
languageCode = "fr-FR"
defaultContentLanguage = "fr"
paginate = "7"
theme = "blib"
enableEmoji = true
#googleAnalytics = "G-XXXXXXXXXX"

################################################################################
# TOP
################################################################################

[params]
fancyTitle = "FESTIVAL BLiB" # title for frontpage, may include image
logo = "images/bliby_rond.png"
copyright = "Festival BLIB"
description = '''
Le BLIB fête ses 10 ans !<br>
Du 14 au 19 avril. <br>
Le grand final au H14 : samedi 19 avril
'''
startbuttonText = "Je prends ma place !"
startbuttonLink = "https://www.helloasso.com/associations/blib"
body_is_markdown = true
extrabuttonText = "Concours brassam"
extrabuttonLink = "posts/brassam"
#custom_css = "foo.css"
#custom_sass = "bar.scss"
# images = ["path_to_social_image_for_link_previews.jpg"]

################################################################################
# MENU
################################################################################

[[params.menu.main]]
url = '/blib'
title = "Festival BLIB"

[[params.menu.main]]
url = '/blib/posts/h14'
title = "Final au H14"

[[params.menu.main]]
url = '/blib/posts/brassam'
title = "Concours Brassam"

[[params.menu.main]]
url = 'https://docs.google.com/forms/d/12DBKenVWmtImmkxeixueG8Vo8-Tg7RaCkwLlJ7ipO4Y/viewform'
title = "Devenir Bénévole"

[[params.menu.main]]
url = '/blib/posts/galerie'
title = "Galeries"

[[params.menu.main]]
url = '/blib/posts/faq'
title = "FAQ"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

################################################################################
# TOP INFOS
################################################################################

[params.one]
enable = true
title = 'Bières Libres & Indépendantes à Bordeaux'
body = '''
Le BLIB est le 1er festival bordelais dédié à la bière artisanale.

Créé en 2015, l’association est menée par un collectif regroupant professionnels indépendants et particuliers, amateurs et connaisseurs du monde brassicole.

Le BLIB a su réunir des brasseries artisanales engagées et un public diversifié dans différents lieux de la métropole qui soutiennent la bière artisanale : bars, caves, restaurants, brasseries etc.
Des dégustations, des rencontres, des ateliers, des conférences.
'''

# [[params.one.icon]]
# icon = "fa-beer"
# style = "1"
# label = "Lorem"

# [[params.one.icon]]
# icon = "fa-heart"
# style = "2"
# label = "Ipsum"

# [[params.one.icon]]
# icon = "solid fa-code"
# style = "3"
# label = "Dolor"

################################################################################
# MIDDLE INFOS
################################################################################

[params.two]
enable = true

[[params.two.section]]
img = "images/visuel_blib2.jpg"
img_alt = "blurry background: white/grey"
title = '6 jours de festivités'
body = "Le BLIB se déroule en région Bordelaise sur un ensemble d'évènements ponctuels du lundi au vendredi et il se termine par un grand final le samedi"

[[params.two.section]]
img = "images/visuel_blib4.png"
title = '30 lieux partenaires'
body = "Un trentaine de lieux partenaires (brasserie, bar, cave, restaurant ...) s'associent chaque année avec nous pour vous proposer des évènements variés autour de la biére (découverte et dégustation) !"

[[params.two.section]]
img = "images/visuel_blib3.png"
title = '60 exposants'
body = '''
Lors du grand final qui se déroule depuis plusieurs années au Hangar 14, tous les exposants, des brasseries aux partenaires de la restauration, se retrouvent pour célébrer la bière craft
'''

################################################################################
# EXPOSANTS
################################################################################
# remove bg: https://www.remove.bg/fr/upload

[params.three]
enable = true
title = 'Exposants 2025'
# body = '''
# '''

# TEMPLATE
#[[params.three.feature]]
#icon = "fa-paper-plane"
#title = "Title"
#body = "body"
# todo (not supported within the template)
#img = "..."

[[params.three.feature]]
title = "Azimut"
body = "Bordeaux (33), France"
link = "https://www.azimutbrasserie.com/"
icon = "test"
logo = "images/logos/azimut.png"

[[params.three.feature]]
title = "Bee King"
body = "Saint Priest (69), France"
link = "https://www.beeking.fr/"
logo = "images/logos/beeking.png"

[[params.three.feature]]
title = "Moustous"
body = "Cours-les-Bains (33), France"
link = "https://www.facebook.com/FermeBrasserieMoustous"
logo = "images/logos/moustous.png"

[[params.three.feature]]
title = "KAPSYL"
body = "Chambray-lés-Tours (37), France"
link = "https://www.instagram.com/brasseriekapsyl/"
logo = "images/logos/kapsyl.png"

[[params.three.feature]]
title = "Jukebox"
body = "Cognac (16), France"
link = "https://brasseriejukebox.com/"
logo = "images/logos/jukebox.png"

[[params.three.feature]]
title = "Effet Papillon"
body = "Mérignac (33), France"
link = "https://www.brasserieffetpapillon.com/"
logo = "images/logos/pap.png"

[[params.three.feature]]
title = "Maison PIP"
body = "Bègles (33), France"
link = "https://maisonpip.com/"
logo = "images/logos/pip.png"

[[params.three.feature]]
title = "La Gang"
body = "Biscarosse (33), France"
link = "https://lagang.fr/"
logo = "images/logos/gang.png"

[[params.three.feature]]
title = "Rosny"
body = "Seignoss (40), France"
link = "https://www.rosny-beer.com/"
logo = "images/logos/rosny.png"

[[params.three.feature]]
title = "Sidras"
body = "Nantes (44), France"
link = "https://www.sidras.fr/"
logo = "images/logos/sidras.png"

[[params.three.feature]]
title = "Zebra"
body = "Preignac (33), France"
link = "https://brasseriezebra.fr/"
logo = "images/logos/zebra.png"

[[params.three.feature]]
title = "Burdigala"
body = "Bordeaux (33), France"
link = "https://www.bieredebordeaux.com/"
logo = "images/logos/burdigala.png"

[[params.three.feature]]
title = "Le bercail WUB"
body = "St-Magne-de-Castillon (33), France"
link = "https://lebercail-wub.fr/"
logo = "images/logos/wub.png"

[[params.three.feature]]
title = "Brasseurs Cueilleurs"
body = "Landrais (17), France"
link = "https://brasseurscueilleurs.fr/"
logo = "images/logos/cueilleurs.png"

[[params.three.feature]]
title = "DWYN"
body = "Montagny (67), France"
link = "https://www.dwynbrewing.com/"
logo = "images/logos/dwyn.png"

################################################################################
# BRASSAM
################################################################################

[params.cta]
enable = true
title = "Concours brassam"
body = "Le concours brassam récompense chaque année le meilleur brassage amateur réalisé pour l'occasion du festival"

[[params.cta.link]]
href = "https://forms.gle/oZyWM27vs234TbDY6"
text = "Inscription"
special = true

[[params.cta.link]]
href = "https://drive.google.com/file/d/166EJDwHGwuAf2WTE6JxzsovlPb4VwVIo/view"
text = "Informations"
special = false

################################################################################
# CONTACT
################################################################################

[params.contact]
email = "asso.blib@gmail.com"
enable = false
# title = "Contacter"
# body = "Hello le BLIB!"
#phone = "+49 (0) 030 000 000"
address = "Bordeaux"
# subject = "New Submission!"
# formspree_form_id = "example_invalid"

################################################################################
# SOCIAL
################################################################################

[params.social]
twitter = ""
mastodon = ""
github = ""
facebook = "AssoBLIB"
youtube = ""
instagram = "festival_blib"
dribble = ""
helloasso = "blib"  ##todo





# language specific options

[languages.fr]
weight = 0
languageName = "French"

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"

[languages.es]
weight = 10
languageName = "Español"
